Context frames can use any delimiter
paninski-lab/lightning-pose pull request #216
Opened 2024-11-07 19:44 UTC by ksikka

As an added bonus this should now work on windows paths. (prior, we were splitting on "/")

2024-11-07 21:50 UTC, themattinthehatt requested changes
looks great! just one request for a type hint

2024-11-07 21:50 UTC, themattinthehatt commented on lightning_pose/data/datasets.py
> +def _get_context_img_paths(center_img_path):
add typehint for `center_img_path`

2024-11-08 17:37 UTC, ksikka commented on lightning_pose/data/datasets.py
> +def _get_context_img_paths(center_img_path):
Added

2024-11-11 13:55 UTC, themattinthehatt approved these changes

2024-11-11 13:55 UTC, merged